### ISSUE TITLE
unrecognized_keys

### ISSUE THREAD

**Issue by issam-seghir** [AngaBlue/express-zod-safe#1]
`router.post("/register", upload.single("picture"), validate(registerSchema), handleNewUser);`

![image](https://github.com/AngaBlue/express-zod-safe/assets/74573675/daa3ed64-f553-4dbd-ba63-9d2d1c5e3893)

my schema : 

```js
// @ts-check

const z = require("zod");
const zu = require("zod_utilz");
const { stringNonEmpty, arrayFromString, formatPath } = require("@/utils/zodUtils");

//? -------- REGEX ---------
const passRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!#$%&*?@])[\d!#$%&*?@A-Za-z]{8,}$/;

//? -------- Sub Schema ---------
const credinalSchema = stringNonEmpty().trim().min(3).max(15);
const infoSchema = z.string().trim().min(3).max(15).optional();

const registerSchema = z.object({
	body: z.object({
		firstName: credinalSchema,
		lastName: credinalSchema,
		email: stringNonEmpty().email().trim().toLowerCase(),
		password: stringNonEmpty().min(8).max(15).regex(passRegex, "Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character (!$%&*?@#)"),
		location: infoSchema,
		job: infoSchema,
	}),
});

module.exports = { registerSchema };
```

**Comment by AngaBlue** [comment]
Can you please try unwrapping the schemas from z.object?  Both the top level object and the body property.  Let me know how that goes.

**Comment by issam-seghir** [comment]
It works thanks , Can I ask how to change the error structure when validating data?

**Comment by AngaBlue** [comment]
This feature I have planned but am yet to implement, it should be quite quick for me to create.

**Comment by AngaBlue** [comment]
@issam-seghir Hi, I've added the ability to specify a custom error handler function in version `v1.2.0`.  Hopefully that's what you were looking for.
